### ISSUE TITLE
Feature : Dataset and Project ID Configuration using .env

### ISSUE THREAD

**Issue by bastianfbr** [jvondermarck/ai-object-detection#1]
## Dataset and Project ID Configuration using .env ⚙️

**Description:**

Currently, the dataset ID and project ID are hardcoded. This issue aims to make them configurable via a `.env` file. 📝

**Proposed Solution:**

1. **.env file utilization:**
    * Add a `.env` file to the project root. 📁
    * Store the dataset ID and project ID as environment variables in the `.env` file. 🌳
    * Utilize the `python-dotenv` library (already installed) to read and load these environment variables into the application's environment. 🔄

2. **Access environment variables:**
    * Access the dataset ID and project ID from the environment variables within the application code. 💻

**Tasks:**

- [ ] Create a `.env` file in the project root. 📁
- [ ] Add `DATASET_ID` and `PROJECT_ID` environment variables to the `.env` file. 📝
- [ ] Update the code to load the environment variables from the `.env` file using `python-dotenv`. 🔄
- [ ] Replace hardcoded IDs with the environment variables in the application code. ✏️
- [ ] Add documentation on how to configure the dataset ID and project ID using the `.env` file. 📖
- [ ] Test the implementation thoroughly. ✅

**Example .env file content:**

```
DATASET_ID=your_dataset_id
PROJECT_ID=your_project_id
```

**Benefits:**

- Improved flexibility and usability. ✨
- Easier configuration for different environments. 🌎
- Enhanced security by avoiding hardcoding sensitive information. 🔒

**Additional Considerations:**

- Consider adding input validation to ensure the provided IDs are valid. ✔️
- Provide clear error messages if the IDs are missing or invalid. ❌
- Document how to configure the dataset ID and project ID using the `.env` file. 📖
- Include the `.env` file in the `.gitignore` to avoid accidentally committing sensitive information to version control. 🙈
