### ISSUE TITLE
Feature : Real-time Metrics Logging to Picsellia

### ISSUE THREAD

**Issue by bastianfbr** [jvondermarck/ai-object-detection#2]
**Description:**

Currently, training metrics (loss, accuracy, etc.) generated by Ultralytics are only accessible via callbacks. This issue aims to enable real-time logging of these metrics to Picsellia. 📈

**Proposed Solution:**

1. **Utilize Ultralytics Callbacks:** Leverage Ultralytics' callback functionality to trigger functions at specific points during training. 
    * Focus on `on_train_epoch_end` and `on_val_end` callbacks to capture and send train/validation metrics, respectively.

2. **Picsellia Integration:**
    * Within the callback functions, integrate with the Picsellia API to log the relevant metrics.
    * Use `experiment.log()` to send metrics to Picsellia with appropriate labels and visualization types (e.g., "line" for accuracy).

**Tasks:**

- [ ] Identify the correct keys within the `trainer.metrics` object to access desired metrics (e.g., accuracy, loss). 🔎
- [ ] Implement callback functions for `on_train_epoch_end` and `on_val_end`. ⚙️
- [ ] Integrate Picsellia's `experiment.log()` within the callback functions to send metrics. 📤
- [ ] Add the callback functions to the Ultralytics model using `model.add_callback()`. 🔗
- [ ] Test the implementation to ensure metrics are logged correctly in real-time on Picsellia. ✅

**Example Code Snippet:**

```python
def on_train_epoch_end(trainer):
    metrics = trainer.metrics
    experiment.log("accuracy", float(metrics["..."]), "line")  # Replace "..." with the correct key

model.add_callback("on_train_epoch_end", on_train_epoch_end) 
```

**Benefits:**

- Real-time monitoring of training progress on Picsellia. 📈
- Improved visibility and analysis of training performance. 👁️‍🗨️
- Facilitates faster identification of potential issues and optimization opportunities. 🚀

**Additional Considerations:**

- Ensure proper error handling for Picsellia API calls. ⚠️
- Consider logging additional metrics beyond accuracy and loss, as needed. ➕
- Document the implementation and usage of the Picsellia logging functionality. 📖
