### ISSUE TITLE
Feature : Implement Inference Pipeline with Model Version from Picsellia

### ISSUE THREAD

**Issue by bastianfbr** [jvondermarck/ai-object-detection#4]
**Description:**

Create a separate inference pipeline 🏗️ that retrieves a specified `model_version` from Picsellia ☁️, downloads the associated `best.pt` model file 📁, and performs inference using Ultralytics 🚀. The pipeline should support three modes: IMAGE 🖼️, VIDEO 📽️, and WEBCAM 💻.

**Proposed Solution:**

1. **Configurable Inference Mode:**
    * Allow users to specify the inference mode (IMAGE 🖼️, VIDEO 📽️, or WEBCAM 💻) through command-line arguments or a configuration file ⚙️.
    * If the mode is IMAGE 🖼️ or VIDEO 📽️, prompt the user for the path to the input file 📂.
    * Utilize the Picsellia SDK 💻 to fetch the desired `model_version` and download the corresponding `best.pt` model file 📁.

2. **Inference Execution:**
    * Use Ultralytics 🚀 to load the downloaded `best.pt` model 🧠.
    * Perform inference based on the selected mode:
        * **IMAGE 🖼️:** Run inference on the provided image file 🖼️.
        * **VIDEO 📽️:** Process the video file frame-by-frame and perform inference on each frame 🎞️.
        * **WEBCAM 💻:** Capture frames from the default webcam and perform real-time inference 🤳.

**Tasks:**

- [ ] Create a new file for the inference pipeline 📄.
- [ ] Implement logic to handle the three inference modes (IMAGE 🖼️, VIDEO 📽️, WEBCAM 💻).
- [ ] Add input validation to ensure valid mode selection and file paths (if applicable) ✔️.
- [ ] Integrate the Picsellia SDK 💻 to retrieve the specified `model_version` and download the `best.pt` model 📁.
- [ ] Utilize Ultralytics 🚀 to load the model 🧠 and perform inference based on the selected mode 💡.
- [ ] Display or save the inference results (e.g., annotated images 🖼️, processed video 📽️, or real-time webcam output 🤳).
- [ ] Test the pipeline thoroughly in all three modes with various input files and model versions ✅.

**Benefits:**

- Enables flexible inference using different input sources (image 🖼️, video 📽️, webcam 💻).
- Leverages Picsellia ☁️ for efficient model version management and retrieval.
- Provides a clear separation between training and inference pipelines 🧱.
- Facilitates easy testing and deployment of trained models 🚀.

**Additional Considerations:**

- Consider adding options for customizing inference settings (e.g., confidence threshold, IoU threshold) 🎚️.
- Implement error handling for invalid inputs, network issues, and model loading failures ⚠️.
- Document the usage and configuration of the inference pipeline 📖.

**Comment by bastianfbr** [comment]
Webcam inference snippet :

```python 
import logging
from ultralytics import YOLO
import cv2

# Configure Ultralytics logs to avoid displaying unnecessary information
logging.getLogger("ultralytics").setLevel(logging.WARNING)

# Load the custom YOLO model
model = YOLO("best.pt")  # Replace "best.pt" with the path to your model

# Open the webcam
cap = cv2.VideoCapture(0)
if not cap.isOpened():
    print("Error: Unable to access the webcam.")
    exit()

# Inference loop
while True:
    ret, frame = cap.read()
    if not ret:
        print("Error: Unable to read the image.")
        break

    # Perform inference with YOLO
    results = model(frame, show=False, conf=0.5)

    # Check and display information if detection
    if results[0].boxes:
        print("\nDetected objects:")
        for box in results[0].boxes:
            # Get coordinates (x1, y1, x2, y2)
            x1, y1, x2, y2 = box.xyxy[0]  # Bounding box coordinates
            confidence = box.conf[0]  # Confidence level
            class_id = int(box.cls[0])  # Class ID
            class_name = model.names[class_id]  # Class name

            # Display details of the detected object
            print(f"- Object: {class_name}")
            print(f"  Coordinates: ({x1:.0f}, {y1:.0f}), ({x2:.0f}, {y2:.0f})")
            print(f"  Confidence: {confidence:.2f}")

    # Annotate the image with the detections
    annotated_frame = results[0].plot()
    cv2.imshow("YOLOv8 Live Inference", annotated_frame)

    # Exit with the 'q' key
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

# Release resources
cap.release()
cv2.destroyAllWindows()`
